### PR TITLE
Update Dockerfile, hopefully making the Docker image work

### PR DESCRIPTION
**Pull request by piperswe**

### CODE REVIEW

**Comment by piperswe** [comment]
IT WORKS YUS I DEBROKED IT

**Comment by ztaylor54** [comment]
Nice job, buddy. Haha

**Comment by piperswe** [comment]
the problem was that docker wasn't installing because it's not meant to be installed in a docker container

**Comment by ztaylor54** [comment]
Makes sense. I saw that you were running an apk install then ditched that

**Pull request merged**
